#define STATUS 0  	/* TREE */
#define SSTATUS 2  	/* OBJECT in TREE #0 */
#define SSTATMSG 3  	/* OBJECT in TREE #0 */
#define SDRIVE 4  	/* OBJECT in TREE #0 */
#define SDRIVMSG 5  	/* OBJECT in TREE #0 */
#define SNAME 6  	/* OBJECT in TREE #0 */
#define SDISKNAM 7  	/* OBJECT in TREE #0 */
#define SFOLDER 8  	/* OBJECT in TREE #0 */
#define SFOLDNAM 9  	/* OBJECT in TREE #0 */
#define SFILE 10  	/* OBJECT in TREE #0 */
#define SFILENAM 11  	/* OBJECT in TREE #0 */
#define SSTRING1 13  	/* OBJECT in TREE #0 */
#define SBUTTON1 24  	/* OBJECT in TREE #0 */
#define SQUIT 27  	/* OBJECT in TREE #0 */
#define SUNDO 28  	/* OBJECT in TREE #0 */
#define DISKS 1  	/* TREE */
#define DTITLE 1  	/* OBJECT in TREE #1 */
#define DINFO2 3  	/* OBJECT in TREE #1 */
#define DINFO1 4  	/* OBJECT in TREE #1 */
#define DSOURCE 5  	/* OBJECT in TREE #1 */
#define DSRCA 7  	/* OBJECT in TREE #1 */
#define DDEST 9  	/* OBJECT in TREE #1 */
#define DDESTA 11  	/* OBJECT in TREE #1 */
#define DINSTALL 27  	/* OBJECT in TREE #1 */
#define DQUIT 28  	/* OBJECT in TREE #1 */
